# Finite Difference Coefficients Calculator
This is a python implementation
[Ref](http://web.media.mit.edu/~crtaylor/calculator.html). 

## How does this work?
Taylor expansion：
$$
f(x+s_{i}) = f(x) + \frac{f'(x)}{1!}s_i + \frac{f''(x)}{2!}s_{i}^{2} + \cdots
$$

Since we require:
$$
\frac{\partial^{d} f}{\partial x^{d}} = c_1\cdot f(x+s_1) + c_2\cdot f(x+s_2) + \cdots + c_n\cdot f(x+s_n)
$$

Then we have:
$$
\begin{bmatrix}
   s_1^0      & \cdots & s_n^0     \\
   \vdots     & \ddots & \vdots    \\
   s_1^{n-1}  & \cdots & s_n^{n-1}
\end{bmatrix}
\begin{bmatrix}
   c_1 \\
   \vdots \\
   c_n
\end{bmatrix} = 
\begin{bmatrix}
   0 \\
   \vdots \\
   d! \\
   \vdots \\
   0
\end{bmatrix}
$$

So we get:
$$
[c_1 \cdots c_n] = [0 \cdots d! \cdots 0]
\begin{bmatrix}
   1      & s_1   & \cdots & s_1^{n-1} \\
   \vdots &\vdots & \ddots & \vdots    \\
   1      & s_n   & \cdots & s_n^{n-1}
\end{bmatrix}^{-1}
$$

The key point is to get the invers of Vandermonde matrix

In [19]:
import numpy as np

In [20]:
# test Vandermonde matrix
x = np.array([2, 3, 5])
vd = np.vander(x, 3, increasing=True)
vd

array([[ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [21]:
# test invers of matrix
np.linalg.inv(vd)

array([[ 5.        , -5.        ,  1.        ],
       [-2.66666667,  3.5       , -0.83333333],
       [ 0.33333333, -0.5       ,  0.16666667]])

In [27]:
def FDCC(S, order=1):
    
    # get Vandermonde matrix
    vd = np.vander(S, len(S), increasing=True)
    
    # set D array base on order
    D = np.zeros_like(S)
    D[order] = np.math.factorial(order)
    
    # calculate parameter array C
    C = np.dot(D, np.linalg.inv(vd))
    
    return C

In [30]:
S = np.array([-1,0,1,3,4])
FDCC(S, 2)

array([ 0.95      , -1.83333333,  0.83333333,  0.08333333, -0.03333333])